# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: goexec
builds:
  - id: backend
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    dir: .
    main: ./cmd
    ldflags: |
      -s -w
      -X github.com/mtrqq/goreleaser-test/lib.Version={{.Version}}
      -X github.com/mtrqq/goreleaser-test/lib.Commit={{.Commit}}
      -X github.com/mtrqq/goreleaser-test/lib.Date={{.Date}}

  # inspired by - https://jondot.medium.com/shipping-rust-binaries-with-goreleaser-d5aa42a46be0
  - id: frontend
    main: hack/dummy.go
    goos:
      - linux
    goarch:
      - amd64
    binary: bundle
    hooks:
      post:
        - rm {{ .Path }}
        - cmd: docker buildx build ../.. -f ../../hack/Dockerfile --output type=local,dest=./bundle
          dir: "{{ dir .Path }}"

archives:
  - id: backend-archive
    format: binary
    builds:
      - backend
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ .Arm }}"
  - id: frontend-archive
    format: tar.gz
    builds:
      - frontend
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: "{{ .ProjectName }}-frontend-bundle"

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - id: backend-docker
    ids:
      - backend
    image_templates:
      - "mtrqq/goexec:{{ .Tag }}"
      - "mtrqq/goexec:v{{ .Major }}"
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    use: buildx

  - id: frontend-docker
    ids:
      - frontend
    dockerfile: frontend/Dockerfile
    image_templates:
      - "mtrqq/goexec-frontend:{{ .Tag }}"
      - "mtrqq/goexec-frontend:v{{ .Major }}"
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    use: buildx

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
