repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
    - id: check-added-large-files
    - id: check-symlinks
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: local
  hooks:
  - id: commit-msg
    name: conventional commit messages
    language: pygrep
    entry: '^(chore|test|feat|fix|build|docs|refactor)!?: ((?!.*(ing))(?!.*(ed))).*$'
  args:
  - --multiline
  - --negate # fails if the entry is NOT matched
  stages:
  - commit-msg
