repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
    - id: check-added-large-files
    - id: check-symlinks
    - id: end-of-file-fixer
    - id: trailing-whitespace
